# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "temurin"
      - name: Compile project
        run: javac projekt-lab/src/*.java -d build
      - name: Check project by running it
        run:  java -classpath "build" Kontroler start
      - name: Run checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.1/checkstyle-10.1-all.jar
          java -jar checkstyle-10.1-all.jar . -c google_checks.xml 
