name: Java CI  # tylko nazwa
on:  # jakie zdarzenia w repozytoriach mają uruchamiać workflow
  push:  # push do repozytorium na każdym branchu
jobs: # lista jobów, które mają się wykonać w ramach danego workflow
  build:  # nazwa joba
    runs-on: ubuntu-latest  # na jakim systemie operacyjnym ma się wykonać akcja
    steps:  # lista kroków do wykonania danego joba
      - uses: actions/checkout@v3  # użycie predefiniowanej akcji z https://github.com/actions/checkout
      - name: Set up JDK 11  # nazwa kroku
        uses: actions/setup-java@v3
        with:  # parametry przekazywane do akcji actions/setup-java
          java-version: '11'
          distribution: "temurin"
      - name: Compile project
        run: javac projekt-lab/src/*.java -d build  # "run" wykonuje komendę/komendy
      - name: Check project by running it
        run:  java -classpath "build" Kontroler start
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: build

  checkstyle:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "temurin"
      - name: Run checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.1/checkstyle-10.1-all.jar
          java -jar checkstyle-10.1-all.jar . -c google_checks.xml